name: Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: checkout Repository
        uses: actions/checkout@v3

      - name: Execute script on server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER _SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        run:
          if ssh -o ConnectionTimeOut=10 ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} exit >> /dev/null; then
             echo "Server Connection Successfull!"
          else
             echo "Server Connection Failed!"
             exit 1
          fi
