name: Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: checkout Repository
        uses: actions/checkout@v3

      - name: Execute script on server
        uses: appleboy/ssh-action@v2
        with:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER _SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      - name: testing
        run:
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} pwd
          
          
